# Generated by Django 5.0.3 on 2024-03-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_banner_banner_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facilties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facilty', models.CharField(max_length=25, verbose_name='Facilty')),
                ('description', models.TextField(verbose_name='Description')),
                ('icon', models.CharField(choices=[('world', 'world'), ('car', 'car'), ('bed', 'bed')], max_length=5, verbose_name='Icons')),
            ],
            options={
                'verbose_name': 'Facilty',
                'verbose_name_plural': 'Facilties',
            },
        ),
    ]
