# Generated by Django 5.0.3 on 2024-03-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_facilties'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilties',
            name='image',
            field=models.ImageField(default=1, upload_to='facilties', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
