# Generated by Django 5.0.3 on 2024-03-26 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_remove_team_pintrest_team_pinterest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
