# Generated by Django 5.0.3 on 2024-03-26 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_delete_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpost',
            name='contact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Contact', to='base.contact'),
            preserve_default=False,
        ),
    ]
