# Generated by Django 5.0.3 on 2024-03-26 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_contactpost_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerpost',
            name='footer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='FooterPosts', to='base.footer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactpost',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ContactPosts', to='base.contact'),
        ),
    ]
