# Generated by Django 5.0.3 on 2024-03-26 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_footerpost_footer_alter_contactpost_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPage',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ImageField(upload_to='team_background', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Worker', 'verbose_name_plural': 'Workers'},
        ),
        migrations.AddField(
            model_name='team',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team_page', to='base.teampage'),
            preserve_default=False,
        ),
    ]
