# Generated by Django 5.0.3 on 2024-03-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_teampage_alter_team_options_team_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teampage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
