# Generated by Django 5.0.3 on 2024-03-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_alter_teampage_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teampage',
            name='background',
            field=models.ImageField(upload_to='team_background', verbose_name='Background'),
        ),
        migrations.AlterField(
            model_name='teampage',
            name='id',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
