# Generated by Django 5.0.3 on 2024-03-26 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_alter_teampage_background_alter_teampage_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footer',
            options={'verbose_name': 'Footer', 'verbose_name_plural': 'Footers'},
        ),
    ]
