# Generated by Django 5.0.3 on 2024-03-26 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_alter_team_team_alter_teampage_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_page', to='base.teampage'),
        ),
    ]
