# Generated by Django 5.0.3 on 2024-03-26 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_alter_team_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team_page', to='base.teampage'),
            preserve_default=False,
        ),
    ]
