# Generated by Django 5.0.3 on 2024-03-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_alter_team_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='image_1',
            field=models.ImageField(upload_to='about_us', verbose_name='Image 1'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='image_2',
            field=models.ImageField(upload_to='about_us', verbose_name='Image 2'),
        ),
    ]
