# Generated by Django 5.0.3 on 2024-03-26 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_alter_aboutus_image_1_alter_aboutus_image_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='banner_text',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='banner_title',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='mini_description',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='price',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='quote',
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_title', models.CharField(max_length=20, verbose_name='Banner_title')),
                ('banner_text', models.TextField(verbose_name='Banner text')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('main_image', models.ImageField(upload_to='main_image', verbose_name='Main image')),
                ('quote', models.TextField(verbose_name='Quote')),
                ('image_1', models.ImageField(upload_to='image_1', verbose_name='Image 1')),
                ('image_2', models.ImageField(upload_to='image_2', verbose_name='Image 2')),
                ('mini_description', models.TextField(verbose_name='Mini description')),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner_page', to='base.banner')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
    ]
