# Generated by Django 5.0.3 on 2024-03-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_remove_banner_banner_text_remove_banner_banner_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='banner_text',
            field=models.TextField(default=1, verbose_name='Banner text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='banner_title',
            field=models.CharField(default=1, max_length=20, verbose_name='Banner_title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='image_1',
            field=models.ImageField(default=1, upload_to='image_1', verbose_name='Image 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='image_2',
            field=models.ImageField(default=1, upload_to='image_2', verbose_name='Image 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='main_image',
            field=models.ImageField(default=1, upload_to='main_image', verbose_name='Main image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='mini_description',
            field=models.TextField(default=1, verbose_name='Mini description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='price',
            field=models.IntegerField(default=1, verbose_name='Price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='quote',
            field=models.TextField(default=1, verbose_name='Quote'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
