# Generated by Django 5.0.3 on 2024-03-26 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_newsbackground'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsbackground',
            options={'verbose_name': 'News_Background', 'verbose_name_plural': 'News_Backgrounds'},
        ),
    ]
