# Generated by Django 5.0.3 on 2024-03-26 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_alter_newsbackground_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPage',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ImageField(upload_to='gallary_background', verbose_name='Background')),
            ],
            options={
                'verbose_name': 'Gallery background',
                'verbose_name_plural': 'Gallery backgrounds',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery', verbose_name='Image')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_page', to='base.gallerypage')),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Galleries',
            },
        ),
    ]
